adding D.Cornet variables and traits
Planteome/CO_343-yam-traits pull request #27
Opened 2022-01-29 12:34 UTC by marieALaporte

Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] An OBO file generated from an OWL file
- [x] New terms
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] Term updates
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] CHECKS
  - [ ] New variables have a parent trait ID 
    - [ ] New variables have methods and scales 
  - [ ] The OBO file has been validated
    - [ ] checked in yambase
    - [ ] checked CropOntology

2022-02-01 16:34 UTC, nmenda requested changes

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
Needs to be YamMethod namespace

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Starch grain size computation
missing definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flour sugar content computation
missing definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flour starch content computation
missing definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
method namespace

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
YamMethod namespace?

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Intensity of tuber flesh oxidation computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
YamMethod namespace

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber color uniformity computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flesh yellowness computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flesh whiteness computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flesh brownness computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flesh color gradient computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Tuber flesh color computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Growth cycle length computation in days between 5% emergence and 95% senescence
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Senescence period duration computation in days between 5 and 95% senescence
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Crop cover compactness computation
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Crop vigor computation in days from median emergence to 80% of maximum ground cover
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: YamScale

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Number of nodes carrying cataphylles before first true leaf counting/plant
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Heterophylly presence estimation nominal 0&1
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: yamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Emergence vigor computation in number of days between 5% and 95% sprouts emergence
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +namespace: YamTrait
namespace: YamMethod

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Latency period duration computation in number of days from planting to 5% sprouts emergence
add definition

2022-02-01 16:34 UTC, nmenda commented on yam-trait-ontology.obo
> +name: Earliness of emergence computation in number of days from planting to 50% sprouts emergence
add definition

2022-02-01 16:42 UTC, nmenda commented
@marieALaporte the variables need a definition, and the new methods need to have a YamMethod namespace. I'll look for the new commit and then test it in YamBase.

2022-02-02 09:41 UTC, marieALaporte reviewed
I fixed the namespaces for methods and scales and added definitons for variables

2022-02-02 09:41 UTC, marieALaporte commented on yam-trait-ontology.obo
> +name: Earliness of emergence computation in number of days from planting to 50% sprouts emergence
done

2022-02-07 16:38 UTC, nmenda approved these changes
Looks good in YamBase!

2022-02-07 16:43 UTC, merged